version: '3'

services:
    streamlit:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: octo_fly_streamlit
        image: dslabocto.azurecr.io/octo_fly_streamlit
        restart: always
        ports:
          - "8501:8501"
        command: streamlit run app/display_predictions.py

    prefect:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: octo_fly_prefect
        image: dslabocto.azurecr.io/octo_fly_prefect
        restart: always
        command: python pipeline/predict.py
